default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: railsgirls_development


test:
  <<: *default
  database: railsgirls_test

production:
  <<: *default
  database: railsgirls_production
  username: railsgirls
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
